### PR TITLE
Use rocm-docs-core for linting

### PR DESCRIPTION
**Pull request by saadrahim**

### CODE REVIEW

**Comment by saadrahim** [comment]
@MathiasMagnus I tried using the scripts but there are some issues here.

**Comment by Maetveis** [comment]
I would prefer to wait for https://github.com/RadeonOpenCompute/rocm-docs-core/issues/489 instead, my reasoning being that GitHub is not the primary platform where development happens for rocRAND, so any issues that this linting would uncover would only come up during the upstreaming pull requests.

**Comment by stanleytsang-amd** [comment]
Seems like there's a bunch of failures in CI and also in the files changed section.

**Comment by stanleytsang-amd** [comment]
PR is stale. Closing.

**Pull request closed without merging**
